name: Tests MacOSX

on:
  push:
  pull_request:
    
jobs:
  build_virus_macrophage:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@10

    - name: Build Virus Macrophage project
      run: |
        make virus-macrophage-sample
        make PHYSICELL_CPP=g++-10
        
    - name: Run Virus Macrophage cell lines project
      run: |
        ./virus-sample


  build_physiboss_cell_lines:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@11
      
    - name: Build PhysiBoSS cell lines project
      run: |
        make physiboss-cell-lines-sample
        make clean
        make PHYSICELL_CPP=g++-11
        
    - name: Run PhysiBoSS cell lines project
      run: |
        ./PhysiBoSS_Cell_Lines
        
  build_spheroid_TNF_model:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run : brew install gcc@11
      
    - name: Build PhysiBoSS TNF project
      run: |
        make physiboss-tnf-model
        make clean
        make PHYSICELL_CPP=g++-11
        
    - name: Run PhysiBoSS TNF project
      run: |
        ./spheroid_TNF_model